/**
 * scripts/build-config.js
 *
 * Generates config.js from environment variables at build time.
 * Runs on Vercel/Netlify via the `build` npm script.
 * Never commits real credentials — they live in the platform's env vars.
 */
const fs = require('fs');

const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];
const missing  = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error(`\n[build-config] Missing environment variables: ${missing.join(', ')}`);
  console.error('Set them in your Vercel / Netlify dashboard and try again.\n');
  process.exit(1);
}

const config = `/* Auto-generated by scripts/build-config.js — DO NOT EDIT */
window.APP_CONFIG = {
  supabase: {
    url:     '${process.env.SUPABASE_URL}',
    anonKey: '${process.env.SUPABASE_ANON_KEY}',
  },
  app: {
    name:            'Centa',
    version:         '${process.env.npm_package_version ?? '1.0.0'}',
    defaultCurrency: '${process.env.DEFAULT_CURRENCY ?? 'LKR'}',
  },
};
`;

fs.writeFileSync('config.js', config);
console.log('[build-config] config.js generated successfully.');
